changelog:
  categories:
    - title: "Features"
      labels:
        - "feat"
      types:
        - "feat"
    - title: "Bug Fixes"
      labels:
        - "fix"
      types:
        - "fix"
    - title: "Performance"
      labels:
        - "perf"
      types:
        - "perf"
    - title: "Other Changes"
      labels:
        - "chore"
        - "refactor"
        - "docs"
        - "test"
        - "ci"
      types:
        - "chore"
        - "refactor"
        - "docs"
        - "test"
        - "ci"
